'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'

type Order = { id: string; provider_order_id?: string; name: string; email: string; phone: string; quantity: number; amount: number; status: string; ticket_code?: string; email_sent_at?: string; whatsapp_sent_at?: string; created_at: string }
type Item = { id: number; title: string; slug: string; description: string; imagePath?: string | null; published: boolean }
type Integration = { configured: boolean; preview: string }
const empty = { title: '', slug: '', description: '', imagePath: '', published: true }
const money = (value: number) => `Rp${Number(value || 0).toLocaleString('id-ID')}`
const integrationLabels: Record<string, string> = { paykita: 'PayKita', resend: 'Resend Email', fonnte: 'Fonnte WhatsApp', blob: 'Vercel Blob' }

export default function AdminPage() {
  const router = useRouter()
  const [tab, setTab] = useState<'orders' | 'content' | 'settings'>('orders')
  const [orders, setOrders] = useState<Order[]>([])
  const [summary, setSummary] = useState({ total: 0, paid: 0, revenue: 0 })
  const [filter, setFilter] = useState('')
  const [items, setItems] = useState<Item[]>([])
  const [form, setForm] = useState(empty)
  const [editing, setEditing] = useState<number | null>(null)
  const [settings, setSettings] = useState({ hero_title: 'Sebuah perjalanan yang tinggal kamu mulai.', hero_description: 'Hadiri performance drama santri Pesantren Jagatarsy untuk mengenalkan budaya Indonesia melalui panggung Dwipantara.', ticket_price: '55000', event_location: 'Jakarta' })
  const [integrations, setIntegrations] = useState<Record<string, Integration>>({})
  const [notice, setNotice] = useState('')

  async function load() {
    const responses = await Promise.all([fetch(`/api/admin/orders${filter ? `?status=${filter}` : ''}`), fetch('/api/admin/content'), fetch('/api/admin/settings'), fetch('/api/admin/integrations')])
    if (responses.some((response) => response.status === 401)) { router.replace('/admin/login'); return }
    const [orderData, contentData, settingData, integrationData] = await Promise.all(responses.map((response) => response.json()))
    setOrders(orderData.orders || []); setSummary(orderData.summary || { total: 0, paid: 0, revenue: 0 }); setItems(contentData.items || []); setSettings((current) => ({ ...current, ...(settingData.settings || {}) })); setIntegrations(integrationData.integrations || {})
  }
  useEffect(() => { load() }, [filter])
  async function saveContent(event: React.FormEvent) { event.preventDefault(); const response = await fetch('/api/admin/content', { method: editing ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(editing ? { ...form, id: editing } : form) }); setNotice(response.ok ? 'Konten berhasil disimpan.' : 'Konten gagal disimpan.'); setForm(empty); setEditing(null); load() }
  async function saveSettings(event: React.FormEvent) { event.preventDefault(); const response = await fetch('/api/admin/settings', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ settings }) }); setNotice(response.ok ? 'Pengaturan website tersimpan.' : 'Pengaturan gagal disimpan.') }
  async function updateOrder(id: string, status: string) { await fetch('/api/admin/orders', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, status }) }); load() }
  async function upload(file?: File) { if (!file) return; const data = new FormData(); data.append('file', file); const response = await fetch('/api/admin/upload', { method: 'POST', body: data }); const result = await response.json(); if (response.ok) setForm((current) => ({ ...current, imagePath: result.url })); setNotice(response.ok ? 'Gambar berhasil diunggah.' : result.error || 'Upload gagal.') }
  async function testIntegration(service: string) { const response = await fetch('/api/admin/integrations', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ service }) }); const result = await response.json(); setNotice(result.message || result.error || 'Status integrasi diperbarui.') }

  return <main className="admin-shell"><header className="admin-header"><div><p className="admin-kicker">DWIPANTARA / CONTROL ROOM</p><h1>Dashboard <em>pentas.</em></h1><p className="admin-muted">Kelola cerita, jadwal, tiket, pembayaran, dan seluruh pengalaman website.</p></div><button className="admin-quiet" onClick={() => router.push('/')}>Lihat website ↗</button></header><nav className="admin-tabs" aria-label="Menu admin"><button className={tab === 'orders' ? 'is-active' : ''} onClick={() => setTab('orders')}>Order tiket</button><button className={tab === 'content' ? 'is-active' : ''} onClick={() => setTab('content')}>Konten utama</button><button className={tab === 'settings' ? 'is-active' : ''} onClick={() => setTab('settings')}>Settings & integrasi</button></nav>
    {tab === 'orders' && <section><div className="admin-stats"><div><span>Total order</span><strong>{summary.total}</strong></div><div><span>Sudah dibayar</span><strong>{summary.paid}</strong></div><div><span>Pendapatan</span><strong>{money(summary.revenue)}</strong></div></div><div className="admin-toolbar"><div><p className="admin-kicker">LIVE ORDER MONITOR</p><h2>Pesanan tiket performance</h2></div><select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="">Semua status</option><option value="pending">Pending</option><option value="paid">Paid</option><option value="failed">Failed</option><option value="cancelled">Cancelled</option></select></div><div className="admin-orders">{orders.length === 0 ? <p className="admin-muted">Belum ada order.</p> : orders.map((order) => <article className="admin-order" key={order.id}><div><p className="admin-order-name">{order.name}</p><p className="admin-muted">{order.email} · {order.phone}</p><p className="admin-muted">{order.provider_order_id || order.id} · {new Date(order.created_at).toLocaleString('id-ID')}</p></div><div className="admin-order-meta"><strong>{money(order.amount)}</strong><span>{order.quantity} tiket</span><span className={`status status-${order.status}`}>{order.status}</span><small>Email: {order.email_sent_at ? 'terkirim' : 'belum'} · WA: {order.whatsapp_sent_at ? 'terkirim' : 'belum'}</small><select value={order.status} onChange={(event) => updateOrder(order.id, event.target.value)}><option value="pending">Pending</option><option value="paid">Paid</option><option value="failed">Failed</option><option value="cancelled">Cancelled</option></select></div></article>)}</div></section>}
    {tab === 'content' && <section className="admin-grid"><form className="admin-editor" onSubmit={saveContent}><p className="admin-kicker">{editing ? 'EDIT KONTEN' : 'KONTEN BARU'}</p><h2>{editing ? 'Ubah cerita' : 'Tambah konten website'}</h2><label>Judul<input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label>Slug<input required value={form.slug} onChange={(event) => setForm({ ...form, slug: event.target.value })} /></label><label>Deskripsi<textarea required rows={6} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><label>Gambar<input type="file" accept="image/*" onChange={(event) => upload(event.target.files?.[0])} /></label><label className="admin-check"><input type="checkbox" checked={form.published} onChange={(event) => setForm({ ...form, published: event.target.checked })} /> Tampilkan di website</label><button className="admin-button">Simpan konten</button></form><div className="admin-list"><div className="admin-section-head"><div><p className="admin-kicker">KONTEN TERBIT</p><h2>Semua konten website</h2></div><span className="admin-count">{items.length} item</span></div><div className="admin-items">{items.map((item) => <article className="admin-item" key={item.id}><div><span className="admin-status">{item.published ? 'TERBIT' : 'DRAFT'}</span><h3>{item.title}</h3><p>{item.description}</p><button className="admin-quiet" type="button" onClick={() => { setEditing(item.id); setForm({ title: item.title, slug: item.slug, description: item.description, imagePath: item.imagePath || '', published: item.published }) }}>Edit</button></div>{item.imagePath ? <img src={item.imagePath} alt="" /> : <div className="admin-image-empty">D</div>}</article>)}</div></div></section>}
    {tab === 'settings' && <section className="admin-settings"><form className="admin-editor" onSubmit={saveSettings}><p className="admin-kicker">PENGATURAN WEBSITE</p><h2>Semua yang tampil di halaman utama</h2><label>Judul utama<textarea rows={2} value={settings.hero_title} onChange={(event) => setSettings({ ...settings, hero_title: event.target.value })} /></label><label>Deskripsi acara<textarea rows={4} value={settings.hero_description} onChange={(event) => setSettings({ ...settings, hero_description: event.target.value })} /></label><label>Harga tiket<input inputMode="numeric" value={settings.ticket_price} onChange={(event) => setSettings({ ...settings, ticket_price: event.target.value })} /></label><label>Lokasi<input value={settings.event_location} onChange={(event) => setSettings({ ...settings, event_location: event.target.value })} /></label><button className="admin-button">Simpan pengaturan</button></form><div className="admin-editor" style={{ marginTop: '1rem' }}><p className="admin-kicker">SECRET STATUS</p><h2>API key & token</h2><p className="admin-muted">Nilai mentah tidak pernah ditampilkan atau disimpan di database. Secret tetap berada di environment project.</p>{Object.entries(integrations).map(([key, integration]) => <div className="admin-item" key={key}><div><h3>{integrationLabels[key] || key}</h3><p>{integration.preview}</p></div><button type="button" className="admin-quiet" onClick={() => testIntegration(key)}>Uji koneksi</button></div>)}</div></section>}
    {notice && <p role="status" className="admin-notice" style={{ maxWidth: 1180, margin: '1rem auto' }}>{notice}</p>}</main>
}
